spring:
  application:
    name: "backend-for-frontend"
  config:
    import: "configserver:http://localhost:8071/"

info:
  app:
    name: "${spring.application.name}"
    description: "BFF Server Application"
    version: "1.0.0"
